name: Python bindings

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  tests_cases:
    name: Tests cases
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Setup requirements
      run: |
        python3 -m pip install -U maturin

    - name: Install local pigment64
      run: python3 -m pip install .

    - name: Run tests
      run: python3 ./tests/test_python.py